packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

overrides:
  '@fastify/ajv-compiler>fast-uri': 3.1.5
  ajv>fast-uri: 3.1.5
  fast-json-stringify>fast-uri: 4.1.2
  fastify>find-my-way: 9.7.0
  next>postcss: 8.5.18
  nanoid: 3.3.18
  next>sharp: 0.35.0
  deepmerge-ts: 8.0.0
